apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.fullname" . }}
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.client }}
      targetPort: {{ .Values.service.ports.client }}
      protocol: TCP
      name: client
    - port: {{ .Values.service.ports.follower }}
      targetPort: {{ .Values.service.ports.follower }}
      protocol: TCP
      name: follower
    - port: {{ .Values.service.ports.election }}
      targetPort: {{ .Values.service.ports.election }}
      protocol: TCP
      name: election
    - port: {{ .Values.service.ports.admin }}
      targetPort: {{ .Values.service.ports.admin }}
      protocol: TCP
      name: admin
  selector:
    {{- include "zookeeper.selectorLabels" . | nindent 4 }}
