---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "keycloak.fullname" . }}-admin
data:
  username: {{ "admin" | b64enc | quote }}
{{- $fullName := include "keycloak.fullname" . }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace ( cat $fullName "-admin" ) }}
{{- if $secret.data }}
  password: {{ $secret.data.password }}
{{- else }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "keycloak.fullname" . }}-tls
type: kubernetes.io/tls
data:
{{ $api := fromYaml ( include "keycloak.certs" . ) }}
  ca.crt: {{ $api.caCert }}
  tls.crt: {{ $api.clientCert }}
  tls.key: {{ $api.clientKey }}
