apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
