apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.credentialSecret.name }}
data:
  username: {{ .Values.database.username | b64enc | quote }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace .Values.database.credentialSecret.name }}
{{- if $secret.data }}
  password: {{ $secret.data.password }}
{{- else }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
