---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openldap.fullname" . }}-ldif-configs
  namespace: {{ .Release.Namespace }}
data:
{{ toYaml .Values.ldifs.configs | indent 2 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openldap.fullname" . }}-ldif-objects
  namespace: {{ .Release.Namespace }}
data:
{{ toYaml .Values.ldifs.objects | indent 2 }}