---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openldap.fullname" . }}
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "openldap.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openldap.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openldap.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: ldap
              containerPort: 1389
              protocol: TCP
{{- if .Values.ldap.tls.enabled }}
            - name: ldaps
              containerPort: 1636
              protocol: TCP
{{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
{{- if .Values.debug }}
            - name: DEBUG
              value: {{ .Values.debug | quote }}
{{- end }}
{{- if .Values.debug_scripts }}
            - name: DEBUG_SCRIPTS
              value: {{ true | quote }}
{{- end }}
            - name: LDAPI
              value: "1"
            - name: LDAP_PORT
              value: "1389"
            - name: LDAP_SUFFIX
              value: {{ .Values.ldap.suffix }}
{{- if .Values.ldap.tls.enabled }}
            - name: LDAPS_PORT
              value: "1636"
            - name: LDAP_TLS_CERT_FILE
              value: "/tls/tls.crt"
            - name: LDAP_TLS_KEY_FILE
              value: "/tls/tls.key"
            - name: LDAP_TLS_CA_FILE
              value: "/tls/ca.crt"
{{- end }}
            - name: CUSTOM_CONFIG_LDIFS
              value: "/ldifs/config"
            - name: CUSTOM_OBJECT_LDIFS
              value: "/ldifs/objects"
            - name: ADMIN_DN
              value: {{ .Values.ldap.admin.dn | default (print "cn=admin," .Values.ldap.suffix ) | quote }}
            - name: ADMIN_PASSWORD
              value: {{ .Values.ldap.admin.password | quote }}
          volumeMounts:
{{- if .Values.ldap.tls.enabled }}
            - name: tls
              mountPath: "/tls"
              readOnly: true
{{- end }}
            - name: data
              mountPath: "/data"
            - name: tmp
              mountPath: "/tmp"
            - name: ldif-configs
              mountPath: "/ldifs/config"
            - name: ldif-objects
              mountPath: "/ldifs/objects"
      volumes:
{{- if .Values.ldap.tls.enabled }}
        - name: tls
          secret:
            secretName: {{ include "openldap.fullname" . }}-tls
{{- end }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "openldap.fullname" . }}-data
        - name: tmp
          emptyDir: {}
        - name: ldif-configs
          configMap:
            name: {{ include "openldap.fullname" . }}-ldif-configs
        - name: ldif-objects
          configMap:
            name: {{ include "openldap.fullname" . }}-ldif-objects
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

