---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "openldap.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
{{ toYaml .Values.storage.accessModes | indent 4 -}}
  {{- if .Values.storage.className }}
  storageClassName: {{ .Values.storage.className | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}