{{- if .Values.ldap.tls.enabled -}}
{{- $cert := fromYaml ( include "openldap.cert" .) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openldap.fullname" . }}-tls
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $cert.ca }}
  tls.crt: {{ $cert.cert }}
  tls.key: {{ $cert.key }}
{{- end }}