{{- if .Values.ldap.tls.enabled -}}
{{- $cert := fromYaml ( include "openldap.cert" .) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openldap.fullname" . }}-tls
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $cert.ca }}
  tls.crt: {{ $cert.cert }}
  tls.key: {{ $cert.key }}
{{- end }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "openldap.fullname" . }}-admin
  namespace: {{ .Release.Namespace }}
data:
  username: {{ "admin" | b64enc }}
  password: {{ include "openldap.admin-password" . }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "openldap.fullname" . }}-config-admin
  namespace: {{ .Release.Namespace }}
data:
  username: {{ "admin" | b64enc }}
  password: {{ include "openldap.admin-password" . }}