---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openldap.fullname" . }}
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.ldaps.type }}
  ports:
    - port: {{ .Values.services.ldap.port }}
      targetPort: ldap
      protocol: TCP
      name: ldap
{{- if .Values.ldap.tls.enabled }}
    - port: {{ .Values.services.ldaps.port }}
      targetPort: ldaps
      protocol: TCP
      name: ldaps
{{- end }}
  selector:
    {{- include "openldap.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openldap.fullname" . }}-ldap
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.ldap.type }}
  ports:
    - port: {{ .Values.services.ldap.port }}
      targetPort: ldap
      protocol: TCP
      name: ldap
  selector:
    {{- include "openldap.selectorLabels" . | nindent 4 }}
{{ if .Values.ldap.tls.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openldap.fullname" . }}-ldaps
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.ldaps.type }}
  ports:
    - port: {{ .Values.services.ldaps.port }}
      targetPort: ldaps
      protocol: TCP
      name: ldaps
  selector:
    {{- include "openldap.selectorLabels" . | nindent 4 }}
{{ end }}