apiVersion: v1
kind: Service
metadata:
  name: {{ include "openldap.fullname" . }}
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.ldap.type }}
  ports:
    - port: {{ .Values.services.ldap.port }}
      targetPort: ldap
      protocol: TCP
      name: ldap
  selector:
    {{- include "openldap.selectorLabels" . | nindent 4 }}
