apiVersion: v1
kind: Service
metadata:
  name: {{ include "openldap.fullname" . }}
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.ldaps.type }}
  ports:
    - port: {{ .Values.services.ldaps.port }}
      targetPort: ldaps
      protocol: TCP
      name: ldaps
  selector:
    {{- include "openldap.selectorLabels" . | nindent 4 }}
